# Generated by Django 3.1.1 on 2020-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_content', models.CharField(max_length=600)),
                ('post_date', models.DateTimeField()),
                ('post_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
