# Generated by Django 3.1.1 on 2021-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
